### ISSUE TITLE
'listen' function unable to bind address

### ISSUE THREAD

**Issue by stonestclair** [Kitura/BlueSocket#199]
My code:
`var buffer = Data()`
`let socket = try! Socket.create(family: .inet, type: .datagram, proto: .udp)`
`_ = try! socket.listen(forMessage: &buffer, on: 50731)`

'listen' throws the error on line 2268 in Socket.swift:
`Error code: -9992(0x-2708), Invalid argument - on 50731`

Due to line 2253 failing to return '0':
`if Darwin.bind(self.socketfd, info!.pointee.ai_addr, info!.pointee.ai_addrlen) == 0 {...`

I've tried multiple different port numbers with multiple iPhones and simulators (both major iOS versions 13 and 14), but it all behaves the same way.

**Comment by dannys42** [comment]
@stonestclair just curious if you found the issue?

**Comment by stonestclair** [comment]
@dannys42 Each line of the code I pasted is in different functions, and I didn't realize that I was using the socket to send a UDP message first before listening on a port. As soon as I got rid of it, listen worked again.

I guessing that by sending first, the socket is getting bound to a different arbitrary port. So now I just have two UDP sockets, one for sending and one for listening.
