### ISSUE TITLE
Echoserver and JavaScript

### ISSUE THREAD

**Issue by Nahatakyan** [Kitura/BlueSocket#210]
Hi. In my case my iOS application needs to be a server, then other iOS apps can connect to it as a client. Now everything works perfectly. Other apps can connect very easily. Now we want to connect to my server from the Web(javascript) and every time we got an error. Can someone show us an example or say how we can do it?

**Comment by billabt** [comment]
Can you post a bit more info?  Specifically what erro you're receiving on client side and maybe a log of what's happening on the server when the error occurred. Thanks.

**Comment by Nahatakyan** [comment]
Front trying to connect with socket.io. In the first time, when client connects, he send this data:
```
Server received from connection at ::1:51265: GET /socket.io/?EIO=4&transport=polling&t=O1X3EZt HTTP/1.1
Host: localhost:1338
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: http://127.0.0.1:5500
DNT: 1
Connection: keep-alive
Referer: http://127.0.0.1:5500/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
```
But the next I have this situation and receiving data did not stop. I want to know if maybe I need to send a response?
<img width="1091" alt="Screen Shot 2022-04-25 at 18 11 38" src="https://user-images.githubusercontent.com/35862561/165106681-2793b0c9-5431-4f1e-8b83-6f4e17ad9852.png">

In javascript written this code:
```
<script src="https://cdn.socket.io/3.1.3/socket.io.min.js" integrity="sha384-cPwlPLvBTa3sKAgddT6krw0cJat7egBga3DJepJyrLl4Q9/5WLra3rrnMcyTyOnh" crossorigin="anonymous"></script>

<script>
    const socket = io("localhost:1337", {
        reconnectionDelay: 5000,
        reconnection:false,
        transports: ["websocket"],
        reconnectionAttempts: 10,
        agent: false,
        upgrade: false,
        rejectUnauthorized: false
    });
    socket.on("connect", (data) => {
        console.log("sdfsdfsdfs");
    });
    socket.on("connect_error", (err) => {
        console.log(err);
    });
</script>
```

**Comment by Nahatakyan** [comment]
I found the solution in WebSocket documentation. Thanks.
